### ISSUE TITLE
Add possibility to add a widget prior to the list

### ISSUE THREAD

**Issue by bezaou** [Dimibe/sticky_grouped_list#10]
Hi, first of all thanks for your package.

Would it be possible to add any new widget prior to the list? returning a custom Widget in the **indexedItemBuilder** on index==0 wouldn't help because any additional widget would still be displayed below the header

**Comment by bezaou** [comment]
I actually add a widget prior to the list using groupSeparatorBuilder

**Comment by Dimibe** [comment]
@bezaou Why would you need to have the widget inside the list. 
I recommend to just have a separate widget before the list.
