### ISSUE TITLE
Customize color for non floatingHeader 

### ISSUE THREAD

**Issue by pkozlovskiy** [Dimibe/sticky_grouped_list#12]
Hardcoded color in this line 
color: widget.floatingHeader ? null : Color(0xffF7F7F7),
make my designer wery  sad(
Please extract in constructor or create builder for all container.

**Comment by Dimibe** [comment]
@pkozlovskiy Just set `floatingHeader` to `true` and define the color in your `groupSeparatorBuilder` by wrapping it with a container. 

I will rework the floating header option soon and let you know.

**Comment by Dimibe** [comment]
@pkozlovskiy In version 1.1.0 a new option `stickyHeaderBackgroundColor` is available. With that option you can set the background color.
