### ISSUE TITLE
Listview reverse

### ISSUE THREAD

**Issue by seranotannason** [Dimibe/sticky_grouped_list#13]
Is it possible to achieve the same effect as setting reverse: true in Listview.builder? For example, a chat screen with ListView.builder(reverse:true, ...) will display the latest messages first and a user has to scroll up to see older messages. Can one do this with StickyGroupedList?

**Comment by Dimibe** [comment]
Hi @seranotannason,
there is an open PR for this exact feature. I haven't had time to review it yet but I'll do so in the next few days.

**Comment by seranotannason** [comment]
Hi @Dimibe, you're right -- how timely! Sorry for the double post, thanks for the quick reply!

**Comment by Dimibe** [comment]
@seranotannason The pull request is merged. Feature is available in version 1.0.0. Please let me know if anything does not work as expected.
