### ISSUE TITLE
How to automatic hide floating header/ not show header

### ISSUE THREAD

**Issue by hikmawanaz** [Dimibe/sticky_grouped_list#21]
Is possible to automatic hide floating header when is not scrolling like in whatsapp?
or permanently hide header, because if I put value floatingheader to false it still show header on the top of the list

**Comment by Dimibe** [comment]
@hikmawanaz This is possible within my other package [grouped_list](https://github.com/Dimibe/grouped_list). 
There is an option `useStickyGroupSeparators` with which you can choose if the top header is sticky or not. The default value is `false`, so this is exactly what you are looking for.
