### ISSUE TITLE
Removing item from the list

### ISSUE THREAD

**Issue by AhmedNourJamalElDin** [Dimibe/sticky_grouped_list#22]
Hello,

Is it possible to remove an item from the list with its header if it's the only message in the group?

TBH when I remove an item, it throws an error stating that invalid index or so.

**Comment by neogn95** [comment]
I believe you will have to refresh the widget with a ChangeNotifier each time you change the source.

**Comment by AhmedNourJamalElDin** [comment]
hmm, ok thanks.
