### ISSUE TITLE
Error _stickyGroupedListViewState == null When resume app from recents 

### ISSUE THREAD

**Issue by khaledkhj** [Dimibe/sticky_grouped_list#42]
Hi,

The following error is causing the widget to crash

`'package:sticky_grouped_list/sticky_grouped_list.dart': Failed assertion: line 392 pos 12: '_stickyGroupedListViewState == null': is not true.`

**Comment by rezashamdani** [comment]
hi, i just remark that and the problem solved for now.

**Comment by Vrajesh-StackApp** [comment]
How to solve this error ??

'package:sticky_grouped_list/sticky_grouped_list.dart': Failed assertion: line 392 pos 12:
 '_stickyGroupedListViewState == null': is not true.

**Comment by AbdulRehman22** [comment]
How to solve
'package:sticky_grouped_list/sticky_grouped_list.dart': Failed assertion: line 392 pos 12:
'_stickyGroupedListViewState == null': is not true.

**Comment by Dimibe** [comment]
Fixed within #48
