### ISSUE TITLE
It is not possible to wrap a column in the Widget StickyGroupedListView.

### ISSUE THREAD

**Issue by rdurelli** [Dimibe/sticky_grouped_list#6]
I tried to wrap StickyGroupedListView with Column... but it didnt work.

**Comment by rdurelli** [comment]
I solve the problem by wrapping StickyGroupedListView with Flexible. `Column(
      children: [
        Text('Here'),
        Flexible(
          child: StickyGroupedListView<SinoElemento, DateTime>(`

**Comment by Dimibe** [comment]
@rdurelli seems like you found a solution yourself. Another option is to use the Expanded-Widget instead of the Flexible-Widget. 
```dart
 Column(
   children: <Widget>[
     Expanded(
       child: StickyGroupedListView<dynamic, String>(),
      ),
    ],
  },
```
