### ISSUE TITLE
Question: How to implement a ScrollController

### ISSUE THREAD

**Issue by cassioseffrin** [Dimibe/sticky_grouped_list#7]
I need to implement an infinity scroll on the StickyGroupedListView. To achieve this it's needed to add a listener to a ScrollController,  when the scroll is changed the method _onScroll is invoked, allowing to insert more records to the stream when the scroll reaches the end.

I can do it with an ordinary ListView ( controller: _scrollController ), however the StickyGroupedListView don't accept a controller but instead a itemScrollController (GroupedItemScrollController), I cannot add a listener to it. 

My question: It's possible  to add a listener to the controller like it's done in ListView: _scrollController.addListener(_onScroll)?

**Comment by Dimibe** [comment]
@cassioseffrin Since the package is build on [scrollable_positioned_list](https://pub.dev/packages/scrollable_positioned_list) you need to define the `itemPositionListener` and add the listener there instead to the `itemScrollController`.

```dart
ItemPositionsListener.create().itemPositions.addListener(_positionListener);
```

You can also find some examples in the scrollable_positioned_list package.

**Comment by cassioseffrin** [comment]
@Dimibe with your help it was easy peasy lemon squeezy! When the scroll is changed the listener is been called.

The last thing I need to do is figure out how to detect the end of scroll. I have the GroupedItemScrollController instead the ScrollController. So I have created my _itemScrollController = GroupedItemScrollController() and set it to the StickyGroupedListView.

```
StickyGroupedListView<ViewPedidos, DateTime>(
              physics: AlwaysScrollableScrollPhysics(),
              itemPositionsListener: _itemPositionsListener,
              itemScrollController: _itemScrollController,
              elements: pedidos,
              order: StickyGroupedListOrder.ASC,
              groupBy: (ViewPedidos element) => DateTime(
                  element.dataAberturaGroup.year,
                  element.dataAberturaGroup.month,
                  element.dataAberturaGroup.day),
              groupSeparatorBuilder: (ViewPedidos element) =>
                  renderDataCabecalho(element),
              itemBuilder: (context, element) {
                return _buildPedidoItemView(element, context);
              },
)
```
My current method with ScrollController to detect the end of scroll is:

 void _onScroll() {
     if (_scrollController.offset + offsetVisibleThreshold >= _scrollController.position.maxScrollExtent) {
         _bloc.loadMoreRecords.add();
      }
  }

How can I do it with GroupedItemScrollController?  I suspect there is a better way.

**Comment by cassioseffrin** [comment]
I managed to do, It's a little tricky than before but it worked. I will appreciate if you could give me an advice, my concerns are related of possible performance issues, this method _onScroll is called several times in a single gesture of scroll. it was a much tricky than a ordinary ScrollController (_scrollController.position.maxScrollExtent)

By the way, I discovered you StickyGroupedListView today and I am already using it.  It's really good widget. I appreciate your efforts in sharing it with the flutter community! 

For my scenario I could simple don't paginate. However performance is fundamental. So I decide implement with streams and paginate the lists from SQLite every time the end of scroll is reached inserting new records. Although StreamBuilder is fast, the database query in a bigger amount of records will end up compromising the performance.

```
  void _onScroll() {
     //The _currentLastIndex will be the index of last record current on the list.
    int currentLastIndex = _itemPositionsListener.itemPositions.value.length;
    bool loadMore = _itemPositionsListener.itemPositions.value
                .firstWhere(
                    (ItemPosition position) =>
                        position.index == _currentLastIndex,
                    orElse: () => null)
                ?.itemTrailingEdge <=
            1.0 ??
        false;

    if (loadMore) {
      _bloc.loadMoreRecords.add();
    }
  }
```

**Comment by cassioseffrin** [comment]
To close this question I will put the final code of my implementation. I end up changing the strategy for my needs. The previews method works but it get invoked every time the current positioned item of each group reach the end of scroll, and that isn't good for infinite scroll. So I have meet my needs using ScrollNotification, as you can see the _onScroll become much simpler.  

```
SingleChildScrollView(
  child: NotificationListener<ScrollNotification>(
      onNotification: (scrollNotification) {
        if (scrollNotification is ScrollEndNotification) {
          _onEndScroll(scrollNotification.metrics);
        }
      },
      child:
          Column(children: <Widget>[
        SizedBox(
          height: MediaQuery.of(context).size.height,
          child: StickyGroupedListView<ViewPedidos, DateTime>(
            physics: AlwaysScrollableScrollPhysics(),
            itemPositionsListener: _itemPositionsListener,
            itemScrollController: _itemScrollController,
            elements: pedidos,
            order: StickyGroupedListOrder.DESC,
            groupBy: (ViewPedidos element) => DateTime(
                element.dataAberturaGroup.year,
                element.dataAberturaGroup.month,
                element.dataAberturaGroup.day),
            groupSeparatorBuilder: (ViewPedidos element) =>
                renderDataCabecalho(element),
            itemBuilder: (context, element) {
              return _buildPedidoItemView(element, context);
            },
          ),
        )
      ])));
```


And then:
```
  _onEndScroll(ScrollMetrics metrics) {
    if (metrics.pixels == metrics.maxScrollExtent) {
      _blocPedidos.setPaginaAtual(_blocPedidos.getPaginaAtualValue + 1);
      _blocPedidos.loadMorePedidosVendedor(1);
    }
  }
```

**Comment by minhdanh** [comment]
@cassioseffrin I'm having same problem and could follow your last method to implement the infinite list. However whenever the list got appended with new items, the StickyGroupedListView is rebuilt and thus the position of the screen is at the top of the list again. Did you have similar problem? If yes, can you share how you got over it?

**Comment by waqadArshad** [comment]
Try this:

```
  groupedItemScrollController.scrollTo(
      index: itemPositionsListener.itemPositions.value.last.index,
      duration: Duration(milliseconds: 100),
  );
```

Please remember to add this:
```
itemPositionsListener: itemPositionsListener, 
```
to your StickyGroupedListView after its declaration, like this:

```
  ItemPositionsListener itemPositionsListener = ItemPositionsListener.create();
```

after adding 

```
  scrollable_positioned_list: ^0.2.3
```
to your pubspec.yaml

**Comment by asadamatic** [comment]
> @cassioseffrin Since the package is build on [scrollable_positioned_list](https://pub.dev/packages/scrollable_positioned_list) you need to define the `itemPositionListener` and add the listener there instead to the `itemScrollController`.
> 
> ```dart
> ItemPositionsListener.create().itemPositions.addListener(_positionListener);
> ```
> 
> You can also find some examples in the scrollable_positioned_list package.

The code to detect min and max scroll positions from [scrollable_positioned_list](https://pub.dev/packages/scrollable_positioned_list)'s example,

```
  itemPositionsListener.itemPositions.addListener(() {

      final positions = itemPositionsListener.itemPositions.value;
      if (positions.isNotEmpty) {
        // Determine the first visible item by finding the item with the
        // smallest trailing edge that is greater than 0.  i.e. the first
        // item whose trailing edge in visible in the viewport.
       final  min = positions
            .where((position) => position.itemTrailingEdge > 0)
            .reduce((min,  position) =>
        position.itemTrailingEdge < min.itemTrailingEdge
            ? position
            : min)
            .index;
        // Determine the last visible item by finding the item with the
        // greatest leading edge that is less than 1.  i.e. the last
        // item whose leading edge in visible in the viewport.
       final max = positions
            .where(( position) => position.itemLeadingEdge < 1)
            .reduce(( max,  position) =>
        position.itemLeadingEdge > max.itemLeadingEdge
            ? position
            : max)
            .index;


       if (!needsScrollToTop.value) {
         if (min >= 10) {
           needsScrollToTop.value = true;
         }
       }
       if (needsScrollToTop.value) {
         if (min < 10) {
           needsScrollToTop.value = false;
         }
       }

      }
    });
```

**Comment by felipegallo** [comment]
I'm having a "strange" problem using the package with a reverse list. The value of my
itemPositionsListener.itemPositions.value in the logs changes, apparently because I apply a "scrollToBottom" every time I load a page (although there is initialIndex, I can't use it for when to view via a search). I have no idea why.
